---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update package manager cache
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
      become: true

  tasks:
  - name: install terminal packages
    package: 
      name: 
        - htop
        - cmatrix
        - figlet
        - cowsay
        - neofetch
        - python3-psutil
        - python3-pip
        - zsh
      state: present

  - name: copy settings.txt to ~/
    become_user: cjwade
    copy:
      src: files/settings.txt
      dest: /home/$USER/settings.txt
      owner: cjwade
      group: cjwade

  - name: Load dconf settings from settings.txt
    become_user: cjwade
    ansible.builtin.shell: "dconf load / < settings.txt"

#  - name: set dash-to-dock preferences
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/shell/extensions/dash-to-dock"
#      value: "['click-action=minimize-or-previews', 'dock-fixed=false', 'dock-position=LEFT', 'extend-height=false', 'hide=false', 'manualhide=false']"
#      value: "['click-action='minimize-or-previews'', 'dock-fixed=false', 'dock-position='LEFT'', 'extend-height=false', 'hide=false', 'manualhide=false']"
#      value: "['click-action='minimize-or-previews'', 'dock-fixed=false', 'dock-position='LEFT'', 'extend-height=false', 'hide=false', 'manualhide=false']"

#  - name: set pop-cosmic workspace preference
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/shell/extensions/pop-cosmic"
#      value: "'workspace-picker-left=false'"

#  - name: set desktop preferences
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/desktop/interface"
#      value: "['clock-show-seconds=false', 'clock-show-weekday=true', 'color-scheme='prefer-dark'', 'enable-animations=false', 'enable-hot-corners=true', 'font-antialiasing='grayscale'', 'font-hinting='slight'', 'toolkit-accessibility=false']"
#      value: "['clock-show-seconds=false', 'clock-show-weekday=true', 'color-scheme=prefer-dark', 'enable-animations=false', 'enable-hot-corners=true', 'font-antialiasing=grayscale', 'font-hinting=slight', 'toolkit-accessibility=false']"

#  - name: set keyboard shortcuts
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/settings-daemon/plugins/media-keys"
#      value: "['email=['<Super>f']', 'home=['<Super>e']']"
#      value: "['email=[<Super>f]', 'home=[<Super>e]']"

#  - name: set program menu preferences
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/desktop/wm/preferences"
#      value: "['button-layout='appmenu:minimize,maximize,close'', 'home=['<Super>e']']"
#      value: "['button-layout=appmenu:minimize,maximize,close', 'home=[<Super>e]']"

  - name: Install MangoHud from GitHub, manually, 1
    package:
      name:
        - build-essential
        - meson
        - ninja-build
        - glslang-tools
        - libx11-dev
        - cmake
        - libxnvctrl-dev
        - libdbus-1-dev
      state: present

  - name: Fix broken installs
    ansible.builtin.shell: apt --fix-broken install

  - name: Install MangoHud from GitHub, manually, 2
    ansible.builtin.shell: pip3 install mako

  - name: install MangoHud from GitHub, manually, 3
    become_user: cjwade
    ansible.builtin.shell: rm -rf MangoHud && git clone --recurse-submodules https://github.com/flightlessmango/MangoHud.git && cd MangoHud && meson build && ninja -C build install && cd ~

  - name: install zsh-syntax-highlighting from GitHub, manually
    become_user: cjwade
    ansible.builtin.shell: rm -rf zsh-syntax-highlighting/ && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

  - name: install zsh-autosuggestions from GitHub, manually
    become_user: cjwade
    ansible.builtin.shell: rm -rf ~/.zsh/zsh-autosuggestions/ && git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

  - name: install graphical packages
    package: 
      name: 
        - alacritty
        - syncthing
        - steam
        - stacer
        - code
        - cura
      state: present

  - name: install libreoffice packages
    package: 
      name: libreoffice
      state: present

#  - name: install yacreader (xUbuntu 22.04)
#    ansible.builtin.shell: echo 'deb http://download.opensuse.org/repositories/home:/selmf/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:selmf.list && curl -fsSL https://download.opensuse.org/repositories/home:selmf/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_selmf.gpg > /dev/null && sudo apt update -y && sudo apt install yacreader -y

#  - name: install discord .deb package
#    ansible.builtin.shell: wget 'https://discord.com/api/download?platform=linux&format=deb' #&& sudo dpkg -i download\?platform=linux\&format=deb

  - name: Ensure fonts directory
    become_user: cjwade
    file:
      path: "/home/$USER/.local/share/fonts"
      state: directory

  - name: Meslo exists
    become_user: cjwade
    shell: "ls /home/$USER/.local/share/fonts/Meslo*"
    register: meslo_exists
    ignore_errors: yes

  - name: Download Meslo
    become_user: cjwade
    when: meslo_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
      dest: "/home/$USER/.local/share/fonts"
      remote_src: yes

  - name: make directory ~/.config/alacritty/
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/.config/alacritty/
    ignore_errors: yes

  - name: make directory ~/.config/MangoHud/
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/.config/MangoHud/
    ignore_errors: yes

  - name: copy alacritty.yml
    become_user: cjwade
    copy:
      src: files/alacritty.yml
      dest: /home/$USER/.config/alacritty/alacritty.yml
      owner: cjwade
      group: cjwade

  - name: copy MangoHud.conf
    become_user: cjwade
    copy:
      src: files/MangoHud.conf
      dest: /home/$USER/.config/MangoHud/MangoHud.conf
      owner: cjwade
      group: cjwade

  - name: copy .zshrc file
    become_user: cjwade
    copy:
      src: files/.zshrc
      dest: /home/$USER/.zshrc
      owner: cjwade
      group: cjwade

  - name: copy .p10k.zsh file
    become_user: cjwade
    copy:
      src: files/.p10k.zsh
      dest: /home/$USER/.p10k.zsh
      owner: cjwade
      group: cjwade

  - name: flatpak present
    ansible.builtin.apt:
      name: flatpak
      state: present

  - name: flathub flatpak repo
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Install Blender as flatpak
    community.general.flatpak:
      name: org.blender.Blender
      state: present
      method: system

  - name: Install Audacity as flatpak
    community.general.flatpak:
      name: org.audacityteam.Audacity
      state: present
      method: system

  - name: Install org.freac.freac as flatpak
    community.general.flatpak:
      name: org.freac.freac
      state: present
      method: system

  - name: Install org.gimp.GIMP as flatpak
    community.general.flatpak:
      name: org.gimp.GIMP
      state: present
      method: system

  - name: Install org.inkscape.Inkscape as flatpak
    community.general.flatpak:
      name: org.inkscape.Inkscape
      state: present
      method: system

  - name: Install fr.handbrake.ghb as flatpak
    community.general.flatpak:
      name: fr.handbrake.ghb
      state: present
      method: system

  - name: Install com.obsproject.Studio as flatpak
    community.general.flatpak:
      name: com.obsproject.Studio
      state: present
      method: system

  - name: Install com.orama_interactive.Pixelorama as flatpak
    community.general.flatpak:
      name: com.orama_interactive.Pixelorama
      state: present
      method: system

  - name: Install org.kde.krita as flatpak
    community.general.flatpak:
      name: org.kde.krita
      state: present
      method: system

  - name: Install com.usebottles.Bottles as flatpak
    community.general.flatpak:
      name: com.usebottles.Bottles
      state: present
      method: user

  - name: Install com.github.tchx84.Flatseal as flatpak
    community.general.flatpak:
      name: com.github.tchx84.Flatseal
      state: present
      method: system

  - name: Install com.mattjakeman.ExtensionManager as flatpak
    community.general.flatpak:
      name: com.mattjakeman.ExtensionManager
      state: present
      method: system

  - name: Install org.godotengine.Godot as flatpak
    community.general.flatpak:
      name: org.godotengine.Godot
      state: present
      method: system

  - name: Install org.mozilla.Thunderbird as flatpak
    community.general.flatpak:
      name: org.mozilla.Thunderbird
      state: present
      method: system

  - name: Install org.freecadweb.FreeCAD as flatpak
    community.general.flatpak:
      name: org.freecadweb.FreeCAD
      state: present
      method: user

  - name: Install org.kicad.KiCad as flatpak
    community.general.flatpak:
      name: org.kicad.KiCad
      state: present
      method: user

  - name: Install org.openscad.OpenSCAD as flatpak
    community.general.flatpak:
      name: org.openscad.OpenSCAD
      state: present
      method: user

  - name: Install net.pcsx2.PCSX2 as flatpak
    community.general.flatpak:
      name: net.pcsx2.PCSX2
      state: present
      method: user

  - name: Install org.DolphinEmu.dolphin-emu as flatpak
    community.general.flatpak:
      name: org.DolphinEmu.dolphin-emu
      state: present
      method: user

  - name: Install org.citra_emu.citra as flatpak
    community.general.flatpak:
      name: org.citra_emu.citra
      state: present
      method: user

  - name: Install org.libretro.RetroArch as flatpak
    community.general.flatpak:
      name: org.libretro.RetroArch
      state: present
      method: user

  - name: Change shell to zsh
    become_user: cjwade
    ansible.builtin.shell: touch "$HOME/.cache/zshhistory" && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k

#  - name: set favorite apps
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/shell"
#      value: "'favorite-apps=['pop-cosmic-launcher.desktop', 'pop-cosmic-workspaces.desktop', 'pop-cosmic-applications.desktop', 'com.alacritty.Alacritty.desktop', 'firefox.desktop', 'org.gnome.Nautilus.desktop', 'vlc.desktop', 'org.mozilla.Thunderbird.desktop', 'code.desktop', 'steam.desktop', 'virt-manager.desktop', 'io.elementary.appcenter.desktop', 'gnome-control-center.desktop']'"

#  - name: set desktop do not disturb
#    become_user: cjwade
#    community.general.dconf:
#      key: "/org/gnome/desktop/notifications"
#      value: "['application-children=['org-gnome-nautilus', 'io-elementary-appcenter', 'org-gnome-gedit', 'com-github-donadigo-eddy', 'gnome-printers-panel', 'firefox', 'vlc', 'org-gnome-lollypop', 'org-gnome-extensions-desktop', 'org-gnome-baobab', 'org-gimp-gimp', 'steam', 'org-kicad-kicad', 'com-alacritty-alacritty']', 'value: 'show-banners=false']"

#  - name: Load dconf settings from settings.txt
#    become_user: cjwade
#    ansible.builtin.shell: "dconf load / < settings.txt"

  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sudge64/ansible_configuration.git