---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Update package manager "apt" cache
    tags: always
    apt: 
      update_cache: yes
      upgrade: 'yes'
    changed_when: false
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: Update package manager "dnf" cache
    tags: always
    dnf: update_cache=yes
    changed_when: false
    when: ansible_distribution in ["Fedora"]

#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base

#- hosts: fedora
#  tags: fedora
#  become: true
#  roles:
#    - fedora

#- hosts: pop!_os
#  tags: pop!_os
#  become: true
#  roles:
#    - pop!_os

  tasks:

  - name: Load Base Tasks
    import_tasks: roles/base/tasks/main.yml

  - name: Load Fedora tasks if ansible distribution is Fedora
    import_tasks: roles/fedora/tasks/main.yml
    when: ansible_distribution in ["Fedora"]

  - name: Load Pop!_OS tasks if ansible distribution is Pop!_OS
    import_tasks: roles/pop!_os/tasks/main.yml
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: copy settings.dconf
    become_user: cjwade
    copy:
      src: files/settings.dconf
      dest: /home/$USER/settings.dconf
      owner: cjwade
      group: cjwade
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

#  - name: Load dconf settings from settings.dconf
#    become_user: cjwade
#    ansible.builtin.shell: cd ~ && dconf load / < settings.dconf
#    args:
#      executable: /bin/bash

  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sudge64/ansible_configuration.git
