---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update package manager "apt" cache
      tags: always
      apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

    - name: Update package manager "dnf" cache
      tags: always
      dnf: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Fedora"]

#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base

#- hosts: workstation
#  tags: workstation
#  become: true
#  roles:
#    - workstation

  tasks:
  
#  - name: copy dnf.conf
#    copy:
#      src: files/dnf.conf
#      dest: /etc/dnf/dnf.conf
#    when: ansible_distribution in ["Fedora"]
  
  - name: Enable RPM Fusion Repos
    ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
    when: ansible_distribution in ["Fedora"]

  - name: Enable RPM Nonfree Repos
    ansible.builtin.shell: sudo dnf install \ https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    when: ansible_distribution in ["Fedora"]  
  
  - name: install terminal packages
    package:
      name:
        - htop
        - cmatrix
        - figlet
        - cowsay
        - neofetch
        - python3-psutil
        - python3-pip
        - zsh
        - dbus-x11
      state: present

  - name: copy settings.dconf
    become_user: cjwade
    copy:
      src: files/settings.dconf
      dest: /home/$USER/settings.dconf
      owner: cjwade
      group: cjwade
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
    
  - name: Install the 'media codecs' package group
    ansible.builtin.shell: dnf groupupdate mutlimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin && dnf groupupdate sound-and-video
    when: ansible_distribution in ["Fedora"]
    
  - name: Install the 'Development tools' package group
    ansible.builtin.dnf:
      name: '@Development tools'
      state: present
    when: ansible_distribution in ["Fedora"]
      
  - name: Install the '@virtualization' package group
    ansible.builtin.dnf:
      name: '@virtualization'
      state: present
    when: ansible_distribution in ["Fedora"]

  - name: Load dconf settings from settings.dconf
    become_user: cjwade
    ansible.builtin.shell: cd ~ && dconf load / < settings.dconf
    args:
      executable: /bin/bash

  - name: Install MangoHud from GitHub 1
    package:
      name:
        - build-essential
        - meson
        - ninja-build
        - glslang-tools
        - libx11-dev
        - cmake
        - libxnvctrl-dev
        - libdbus-1-dev
      state: present
    ignore_errors: yes

  - name: Fix broken installs
    ansible.builtin.shell: apt --fix-broken install
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: Install MangoHud from GitHub 2
    ansible.builtin.pip:
      name: mako
      executable: pip3

  - name: Install MangoHud from GitHub 3
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/MangoHud
    ignore_errors: yes

  - name: Install MangoHud from GitHub 4
    become_user: cjwade
    ansible.builtin.git:
      repo: https://github.com/flightlessmango/MangoHud.git
      dest: /home/cjwade/MangoHud
      clone: yes
      update: yes

  - name: Install MangoHud from GitHub 5
    become_user: cjwade
    ansible.builtin.shell: cd MangoHud && meson build && ninja -C build install && cd ..
    ignore_errors: yes

  - name: Install zsh-syntax-highlighting from GitHub
    become_user: cjwade
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: /home/cjwade/.zsh/zsh-syntax-highlighting
      clone: yes
      update: yes

  - name: Install zsh-syntax-highlighting from GitHub
    become_user: cjwade
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/cjwade/.zsh/zsh-autosuggestions
      clone: yes
      update: yes

  - name: install graphical packages
    package:
      name:
        - kitty
        - syncthing
        - steam
        - stacer
        - code
        - cura
        - gnome-tweaks
        - vlc
        - flameshot
      state: present
    ignore_errors: yes

  - name: install libreoffice packages
    package:
      name: libreoffice
      state: present
    ignore_errors: yes

  - name: install nautilus add-in packages (nautilus-image-converter & gnome-sushi)
    package:
      name:
        - nautilus-image-converter
        - gnome-sushi
      state: present
    ignore_errors: yes

  - name: Ensure fonts directory
    become_user: cjwade
    file:
      path: "/home/$USER/.local/share/fonts"
      state: directory

  - name: Meslo exists
    become_user: cjwade
    shell: "ls /home/$USER/.local/share/fonts/Meslo*"
    register: meslo_exists
    ignore_errors: yes

  - name: Download Meslo
    become_user: cjwade
    when: meslo_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
      dest: "/home/$USER/.local/share/fonts"
      remote_src: yes

  - name: make directory ~/.config/kitty/
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/.config/kitty/
    ignore_errors: yes

  - name: make directory ~/.config/MangoHud/
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/.config/MangoHud/
    ignore_errors: yes

  - name: copy kitty.conf
    become_user: cjwade
    copy:
      src: files/kitty.conf
      dest: /home/$USER/.config/kitty/kitty.conf
      owner: cjwade
      group: cjwade

  - name: copy MangoHud.conf
    become_user: cjwade
    copy:
      src: files/MangoHud.conf
      dest: /home/$USER/.config/MangoHud/MangoHud.conf
      owner: cjwade
      group: cjwade

  - name: copy .zshrc file
    become_user: cjwade
    copy:
      src: files/.zshrc
      dest: /home/$USER/.zshrc
      owner: cjwade
      group: cjwade

  - name: copy .p10k.zsh file
    become_user: cjwade
    copy:
      src: files/.p10k.zsh
      dest: /home/$USER/.p10k.zsh
      owner: cjwade
      group: cjwade

  - name: flatpak present
    ansible.builtin.apt:
      name: flatpak
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: flathub flatpak repo
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system

  - name: Install Blender as flatpak
    community.general.flatpak:
      name: org.blender.Blender
      state: present
      method: system

  - name: Install Audacity as flatpak
    community.general.flatpak:
      name: org.audacityteam.Audacity
      state: present
      method: system

  - name: Install org.freac.freac as flatpak
    community.general.flatpak:
      name: org.freac.freac
      state: present
      method: system

  - name: Install org.gimp.GIMP as flatpak
    community.general.flatpak:
      name: org.gimp.GIMP
      state: present
      method: system

  - name: Install org.inkscape.Inkscape as flatpak
    community.general.flatpak:
      name: org.inkscape.Inkscape
      state: present
      method: system

  - name: Install fr.handbrake.ghb as flatpak
    community.general.flatpak:
      name: fr.handbrake.ghb
      state: present
      method: system

  - name: Install com.obsproject.Studio as flatpak
    community.general.flatpak:
      name: com.obsproject.Studio
      state: present
      method: system

  - name: Install com.orama_interactive.Pixelorama as flatpak
    community.general.flatpak:
      name: com.orama_interactive.Pixelorama
      state: present
      method: system

  - name: Install org.kde.krita as flatpak
    community.general.flatpak:
      name: org.kde.krita
      state: present
      method: system

  - name: Install com.usebottles.Bottles as flatpak
    community.general.flatpak:
      name: com.usebottles.bottles
      state: present
      method: system

  - name: Install com.github.tchx84.Flatseal as flatpak
    community.general.flatpak:
      name: com.github.tchx84.Flatseal
      state: present
      method: system

  - name: Install com.mattjakeman.ExtensionManager as flatpak
    community.general.flatpak:
      name: com.mattjakeman.ExtensionManager
      state: present
      method: system

  - name: Install org.godotengine.Godot as flatpak
    community.general.flatpak:
      name: org.godotengine.Godot
      state: present
      method: system

  - name: Install org.mozilla.Thunderbird as flatpak
    community.general.flatpak:
      name: org.mozilla.Thunderbird
      state: present
      method: system

  - name: Install org.freecadweb.FreeCAD as flatpak
    community.general.flatpak:
      name: org.freecadweb.FreeCAD
      state: present
      method: system

  - name: Install org.kicad.KiCad as flatpak
    community.general.flatpak:
      name: org.kicad.KiCad
      state: present
      method: system

  - name: Install org.openscad.OpenSCAD as flatpak
    community.general.flatpak:
      name: org.openscad.OpenSCAD
      state: present
      method: system

  - name: Install net.pcsx2.PCSX2 as flatpak
    community.general.flatpak:
      name: net.pcsx2.PCSX2
      state: present
      method: system

  - name: Install org.DolphinEmu.dolphin-emu as flatpak
    community.general.flatpak:
      name: org.DolphinEmu.dolphin-emu
      state: present
      method: system

  - name: Install org.citra_emu.citra as flatpak
    community.general.flatpak:
      name: org.citra_emu.citra
      state: present
      method: system

  - name: Install org.libretro.RetroArch as flatpak
    community.general.flatpak:
      name: org.libretro.RetroArch
      state: present
      method: system

  - name: Install net.davidotek.pupgui2 (protonup-qt) as flatpak
    community.general.flatpak:
      name: net.davidotek.pupgui2
      state: present
      method: system

  - name: Touch /home/$USER/.cache/zshhistory"
    become_user: cjwade
    ansible.builtin.file:
      path: /home/$USER/.cache/zshhistory
      state: touch

  - name: Install powerlevel10k
    become_user: cjwade
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: /home/cjwade/.zsh/powerlevel10k
      clone: yes
      update: yes
      depth: 1

  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sudge64/ansible_configuration.git
