---
- name: Enable RPM Fusion Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  when: ansible_distribution in ["Fedora", "Nobara"]

- name: Enable RPM Nonfree Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  when: ansible_distribution in ["Fedora", "Nobara"]

#- name: Install the 'media codecs' package group
#  ansible.builtin.dnf:
#    name:
#      - gstreamer1
#      - gstreamer1-plugin-openh264 
#      - lame
#    state: present
#  when: ansible_distribution in ["Fedora"]
    
#- name: Group Upgrade with Multimedia
#  ansible.builtin.shell: sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel && sudo dnf install lame\* --exclude=lame-devel && dnf group upgrade --with-optional Multimedia
#  #when: ansible_distribution in ["Fedora"]
#  ignore_errors: yes
    
- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name: '@development tools'
    state: present
      
- name: Install the '@virtualization' package group
  ansible.builtin.dnf:
    name: '@virtualization'
    state: present
    
- name: Install the '@C development tools and libraries' package group
  ansible.builtin.dnf:
    name: '@c development tools and libraries'
    state: present

- name: install neovim dependencies for Debian systems
  package:
    name:
      - python3.10-venv
      - ninja-build
      - libtool
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - gettext
      - curl
    state: present
  ignore_errors: yes

- name: Install VS Codium Repo 1
  ansible.builtin.shell: sudo rpmkeys --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg

- name: Install VS Codium Repo 2
  ansible.builtin.shell: printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=download.vscodium.com\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/yum.repos.d/vscodium.repo

- name: Update package manager "dnf" cache
  tags: always
  dnf: update_cache=yes
  changed_when: false

- name: Install VS Codium
  package: codium
  state: present
  ignore_errors: yes
