---
- name: Enable RPM Fusion Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

- name: Enable RPM Nonfree Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  
- name: Install the 'media codecs' package group
  ansible.builtin.dnf:
    name:
      - gstreamer1
      - gstreamer1-plugin-openh264 
      - lame
    state: present
  when: ansible_distribution in ["Fedora"]
    
- name: Group Upgrade with Multimedia
  ansible.builtin.shell: group upgrade --with-optional Multimedia
  when: ansible_distribution in ["Fedora"]
    
- name: Install the 'Development tools' package group
  ansible.builtin.dnf:
    name: '@development tools'
    state: present
  when: ansible_distribution in ["Fedora"]
      
- name: Install the '@virtualization' package group
  ansible.builtin.dnf:
    name: '@virtualization'
    state: present
  when: ansible_distribution in ["Fedora"]
    
- name: Install the '@C development tools and libraries' package group
  ansible.builtin.dnf:
    name: '@c development tools and libraries'
    state: present
  when: ansible_distribution in ["Fedora"]
