---
- name: flatpak present
  ansible.builtin.apt:
    name: flatpak
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
   
- name: flatpak present
  ansible.builtin.dnf:
    name: flatpak
    state: present
  when: ansible_distribution in ["Fedora"]

- name: flathub flatpak repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: flatpak flatpak repo dnf
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  when: ansible_distribution in ["Fedora"]

- name: Install Blender as flatpak
  community.general.flatpak:
    name: org.blender.Blender
    state: present
    method: system

- name: Install Audacity as flatpak
  community.general.flatpak:
    name: org.audacityteam.Audacity
    state: present
    method: system

- name: Install org.freac.freac as flatpak
  community.general.flatpak:
    name: org.freac.freac
    state: present
    method: system

- name: Install org.gimp.GIMP as flatpak
  community.general.flatpak:
    name: org.gimp.GIMP
    state: present
    method: system
  when:
    - org.gimp.GIMP is defined
    - org.gimp.GIMP == true

- name: Install org.inkscape.Inkscape as flatpak
  community.general.flatpak:
    name: org.inkscape.Inkscape
    state: present
    method: system

- name: Install fr.handbrake.ghb as flatpak
  community.general.flatpak:
    name: fr.handbrake.ghb
    state: present
    method: system

- name: Install com.obsproject.Studio as flatpak
  community.general.flatpak:
    name: com.obsproject.Studio
    state: present
    method: system

- name: Install com.orama_interactive.Pixelorama as flatpak
  community.general.flatpak:
    name: com.orama_interactive.Pixelorama
    state: present
    method: system

- name: Install org.kde.krita as flatpak
  community.general.flatpak:
    name: org.kde.krita
    state: present
    method: system

- name: Install com.usebottles.Bottles as flatpak
  community.general.flatpak:
    name: com.usebottles.bottles
    state: present
    method: system

- name: Install com.github.tchx84.Flatseal as flatpak
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present
    method: system

- name: Install com.mattjakeman.ExtensionManager as flatpak
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: present
    method: system

- name: Install org.godotengine.Godot as flatpak
  community.general.flatpak:
    name: org.godotengine.Godot
    state: present
    method: system

- name: Install org.mozilla.Thunderbird as flatpak
  community.general.flatpak:
    name: org.mozilla.Thunderbird
    state: present
    method: system

- name: Install org.freecadweb.FreeCAD as flatpak
  community.general.flatpak:
    name: org.freecadweb.FreeCAD
    state: present
    method: system

- name: Install org.kicad.KiCad as flatpak
  community.general.flatpak:
    name: org.kicad.KiCad
    state: present
    method: system

- name: Install org.openscad.OpenSCAD as flatpak
  community.general.flatpak:
    name: org.openscad.OpenSCAD
    state: present
    method: system

- name: Install net.pcsx2.PCSX2 as flatpak
  community.general.flatpak:
    name: net.pcsx2.PCSX2
    state: present
    method: system

- name: Install org.DolphinEmu.dolphin-emu as flatpak
  community.general.flatpak:
    name: org.DolphinEmu.dolphin-emu
    state: present
    method: system

- name: Install org.citra_emu.citra as flatpak
  community.general.flatpak:
    name: org.citra_emu.citra
    state: present
    method: system

- name: Install org.libretro.RetroArch as flatpak
  community.general.flatpak:
    name: org.libretro.RetroArch
    state: present
    method: system
  when:
    - libretro is defined
    - libretro == true

- name: Install net.davidotek.pupgui2 (protonup-qt) as flatpak
  community.general.flatpak:
    name: net.davidotek.pupgui2
    state: present
    method: system
  when:
    - net.davidotek.pupgui2 is defined
    - net.davidotek.pupgui2 == true

