---
  - name: Install MangoHud from GitHub 1
    package:
      name:
        - build-essential
        - meson
        - ninja-build
        - glslang-tools
        - libx11-dev
        - cmake
        - libxnvctrl-dev
        - libdbus-1-dev
      state: present
    ignore_errors: yes

  - name: Fix broken installs
    ansible.builtin.shell: apt --fix-broken install
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: Install MangoHud from GitHub 2
    ansible.builtin.pip:
      name: mako
      executable: pip3

  - name: Install MangoHud from GitHub 3
    become_user: cjwade
    ansible.builtin.shell: mkdir /home/$USER/MangoHud
    ignore_errors: yes

  - name: Install MangoHud from GitHub 4
    become_user: cjwade
    ansible.builtin.git:
      repo: https://github.com/flightlessmango/MangoHud.git
      dest: /home/cjwade/MangoHud
      clone: yes
      update: yes

  - name: Install MangoHud from GitHub 5
    become_user: cjwade
    ansible.builtin.shell: cd MangoHud && meson build && ninja -C build install && cd ..
    ignore_errors: yes