---
- name: Install zsh-syntax-highlighting from GitHub
  become_user: cjwade
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/cjwade/.zsh/zsh-syntax-highlighting
    clone: yes
    update: yes

- name: Install zsh-syntax-highlighting from GitHub
  become_user: cjwade
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/cjwade/.zsh/zsh-autosuggestions
    clone: yes
    update: yes

- name: Install powerlevel10k
  become_user: cjwade
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/cjwade/.zsh/powerlevel10k
    clone: yes
    update: yes
    depth: 1