---
- name: install terminal packages
  package:
    name:
      - htop
      - cmatrix
      - figlet
      - cowsay
      - neofetch
      - python3-psutil
      - python3-pip
      - zsh
      - dbus-x11
      - cifs-utils
    state: present
    
- name: install graphical packages
  package:
    name:
      - kitty
      - syncthing
      - steam
      - stacer
      - code
      - cura
      - gnome-tweaks
      - vlc
      - flameshot
#      - protontricks
    state: present
  ignore_errors: yes

- name: install libreoffice packages
  package:
    name: libreoffice
    state: present
  ignore_errors: yes

- name: install nautilus add-in packages (nautilus-image-converter & gnome-sushi)
  package:
    name:
      - nautilus-image-converter
      - gnome-sushi
    state: present
  ignore_errors: yes