---
- name: install terminal packages
  package:
    name:
      - htop
      - cmatrix
      - figlet
      - cowsay
      - neofetch
      - python3-psutil
      - python3-pip
      - zsh
      - dbus-x11
      - cifs-utils
      - rpcbind
      - nfs-common
    state: present
  ignore_errors: yes
    
- name: install graphical packages
  package:
    name:
      - kitty
      - syncthing
      - steam
      - stacer
      - gnome-tweaks
      - vlc
      - flameshot
    state: present
  ignore_errors: yes

- name: Install crablang (rust fork)
  ansible.builtin.shell: sh <(curl https://install.crablang.org -L)
  ignore_errors: yes

- name: install libreoffice packages
  package:
    name: libreoffice
    state: present
  ignore_errors: yes

- name: install nautilus add-in packages (nautilus-image-converter & gnome-sushi)
  package:
    name:
      - nautilus-image-converter
      - gnome-sushi
    state: present
  ignore_errors: yes
