---
- name: install terminal packages
  package:
    name:
      - htop
      - cmatrix
      - figlet
      - cowsay
      - neofetch
      - python3-psutil
      - python3-pip
      - zsh
      - dbus-x11
      - cifs-utils
      - rpcbind
      - nfs-common
      - python3.10-venv
    state: present
    
- name: install graphical packages
  package:
    name:
      - kitty
      - syncthing
      - steam
      - stacer
      - code
      - gnome-tweaks
      - vlc
      - flameshot
    state: present
  ignore_errors: yes

- name: Install RUST via rustup
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  ignore_errors: yes

- name: install libreoffice packages
  package:
    name: libreoffice
    state: present
  ignore_errors: yes

- name: install nautilus add-in packages (nautilus-image-converter & gnome-sushi)
  package:
    name:
      - nautilus-image-converter
      - gnome-sushi
    state: present
  ignore_errors: yes