---
- name: Enable RPM Fusion Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
  when: ansible_distribution in ["ArchLinux"]

- name: Enable RPM Nonfree Repos
  ansible.builtin.shell: dnf install \ https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  when: ansible_distribution in ["ArchLinux"]

